module.exports = {
    categories: {
        Technology: [
            "AI",
            "Blockchain",
            "Machine Learning",
            "Cybersecurity",
            "Robotics",
            "IoT",
            "Big Data",
            "Cloud Computing",
            "VR",
            "AR",
            "Quantum Computing",
            "SaaS",
            "Data Science",
            "FinTech",
            "Mobile Apps",
            "Web Development",
            "Drones",
            "Automation",
            "Digital Transformation",
            "Smart Cities",
            "APIs",
            "Software Development",
            "Renewable Tech",
            "Startup Tech",
            "Tech Gadgets",
        ],
        Media: [
            "Film",
            "Photography",
            "Documentaries",
            "Cinematography",
            "Screenwriting",
            "Directing",
            "Editing",
            "VFX",
            "Indie Movies",
            "Production",
            "Sound Design",
            "Storyboarding",
            "Casting",
            "Film Festivals",
            "Acting",
            "Film Distribution",
            "Music",
            "Songwriting",
            "Music Production",
            "Recording",
            "Sound Mixing",
            "Music Videos",
            "Album Releases",
            "Streaming",
        ],
        Gaming: [
            "Video Games",
            "Mobile Games",
            "Game Development",
            "Game Design",
            "Indie Games",
            "Board Games",
            "RPGs",
            "VR Gaming",
            "AR Gaming",
            "Esports",
            "Multiplayer Games",
            "Unity",
            "Unreal Engine",
            "Game Music",
            "Game Storylines",
        ],
        Health: [
            "Yoga",
            "Meditation",
            "Fitness",
            "Dieting",
            "Mental Health",
            "Home Workouts",
            "Supplements",
            "Alternative Medicine",
            "Physiotherapy",
            "Well-being Apps",
            "Personal Training",
            "Outdoor Activities",
        ],
        Education: [
            "E-learning",
            "Online Courses",
            "Tutoring",
            "STEM",
            "Homeschooling",
            "EdTech",
            "Workshops",
            "Training Programs",
            "Classroom Tools",
            "Curriculum Development",
        ],
        Social: [
            "Nonprofits",
            "Community Projects",
            "Social Innovation",
            "Volunteering",
            "Activism",
            "Philanthropy",
            "Fundraising",
        ],
        Environment: [
            "Climate Change",
            "Sustainability",
            "Green Energy",
            "Eco-Friendly Products",
            "Recycling",
            "Wildlife Conservation",
            "Environmental Activism",
            "Water Conservation",
            "Urban Gardening",
        ],
        Food: [
            "Cooking",
            "Baking",
            "Gourmet",
            "Vegan Recipes",
            "Food Startups",
            "Food Trucks",
            "International Cuisine",
            "Organic Food",
            "Desserts",
            "Food Photography",
        ],
        Fashion: [
            "Fashion Design",
            "Streetwear",
            "Sustainable Fashion",
            "Luxury Brands",
            "Textile Innovation",
            "Fashion Shows",
            "Accessories",
            "Jewelry Design",
        ],
        Science: [
            "Space Exploration",
            "Biotechnology",
            "Physics",
            "Chemistry",
            "Neuroscience",
            "Medical Research",
            "Quantum Physics",
            "Scientific Publishing",
            "AI in Science",
        ],
        Travel: [
            "Backpacking",
            "Adventure Travel",
            "Luxury Travel",
            "Cultural Exploration",
            "Eco-Tourism",
            "Van Life",
            "Travel Photography",
            "Travel Blogging",
        ],
        Home: [
            "Interior Design",
            "Home Automation",
            "Smart Home Gadgets",
            "Minimalist Living",
            "DIY Home Projects",
            "Sustainable Homes",
            "Real Estate",
        ],
    },
};
